name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t weather-pipeline-airflow:${{ github.sha }} .

      - name: Tag as latest
        run: docker tag weather-pipeline-airflow:${{ github.sha }} weather-pipeline-airflow:latest
